### ISSUE TITLE
[feature/multi_module] Clean Architecture Multi Module

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#19]
## Description
클린아키텍처 레이어별로 모듈화한다.

## To-do
- [x] 클린아키텍처의 각 레이어에 포함되어있는 패키지를 구성한다.
- [x] 각 레이어로 모듈화한다.
- [x] 의존성주입, Network, Repository, UseCase 작성한다.
- [x] 테스트 url을 통해서 실제 api통신하여 결과를 확인한다.
