### ISSUE TITLE
[feature/select_screen] 학교 선택화면 구현

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#26]
## Description
스플래시 이후 나타나는 학교 선택화면을 구현한다.

## To-do
- [x] LazyColumn 을 사용하여 학교 리스트를 나타낸다.
- [x] 화면에 필요한 버튼을 공용 유틸로 구현한다.
- [x] 스플래시 애니메이션 종료 후 학교 선택화면으로 이동한다.
- [x] 학교 신청하러가기 레이아웃 구현한다.
