### ISSUE TITLE
[feature/theme] 앱 테마, 컬러 기본 스타일 설정

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#28]
## Description
뷰를 작업하면서 공통적으로 들어갈 컬러, 기본스타일, 테마 설정

## To-do
- [x] 공통 컬러 설정
- [x] 공통 폰트 설정
- [x] 공통 테마 설정
- [x] 다크모드 제거

**Comment by SsongSik** [comment]
공통 컬러는 추 후에 추가
