### ISSUE TITLE
[feature/bottom] Bottom Navigation 4개 화면 초기셋팅

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#33]
## Description
앱 메인화면의 4개 바텀네비게이션 탭과 4개 화면 설정

## To-do
- [x] MainActivity에서 BottomNavigation 설정
- [x] 4개의 화면 구성
- [x] BottomNavigation과 4개의 화면 연결 및 테스트
- [x] radius, border 적용
