### ISSUE TITLE
[feature/home] 홈 화면 맛집모아보기까지 구현

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#36]
## Description
앱의 메인화면인 홈 화면을 구현한다.

## To-do
- [x] 탑 App Bar 구현
- [x] 제일 상단 카테고리 레이아웃 구현
- [x] 맛집 모아보기 레이아웃 구현
