### ISSUE TITLE
[feature/category] 카테고리 상세 리스트 화면 완성하기

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#58]
## Description
카테고리 상세 리스트 화면 완성하기

## To-do
- [x] 정렬순서 다이얼로그 완성
- [x] 신고하기 바텀시트 다이얼로그 완성
- [x] 카테고리 다이얼로그 완성
- [x] 별점순 바텀시트다이얼로그 구현
