### ISSUE TITLE
[feature/detail_restaurant] 식당 상세화면 구현

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#62]
## Description
식당 상세 화면을 구현한다.

## To-do
- [x] 상단 이미지 구현
- [x] 이미지 밑 탑바 이름, 좋아요, 공유하기 구현
- [x] 3개 탭 레이아웃 구성
- [x] 3개 탭 레이아웃에 들어갈 화면 구현
