### ISSUE TITLE
[feature/api_get_university] 대학 목록 조회 API 연결

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#83]
## Description
대학 목록 조회 API 연결

## To-do
- [x] 클린아키텍쳐 구조 구성
- [x] 대학 목록 조회 API 연결
- [x] Mock Data 삭제 및 목록 조회 Response 뷰 연결 
- [x] 에브리밀 로딩 추가
- [x] 에러다이얼로그 추가
