### ISSUE TITLE
[feature/get_detail_restaurant] 대학교 주변 식당 type추가 및 식당 상세화면 api 연결

### ISSUE THREAD

**Issue by SsongSik** [everymeals/EveryMeal_Android#91]
## Description
대학교 주변 식당 type추가 및 식당 상세화면 api 연결

## To-do
- [x] 식당 상세화면 navigate 연결
- [x] 식당 인덱스값 전달
- [x] 식당 상세화면 api 연결
